#!/usr/bin/python
'''
This python script enables the user to query the DuckDuckGo Search API through the 
command line.

Usage:
	ddg 1+1 --> one-time search
	ddg	--> interactive mode with history
'''
import os
import sys
import urllib
import json
import re
if not os.name=='nt':
	import readline #enables arrow keys and history

def search(query):
	f = urllib.urlopen("http://api.duckduckgo.com/?format=json&no_redirects=1&no_html=1&q="+urllib.quote_plus(query))
	resp = json.load(f)
	types={'A':'article','D':'disambiguation','C':'category','N':'name','E':'exclusive'}
	if resp['Type']=='':
		print("No results returned")
		return
	print('['+types[resp['Type']]+']')
	if not resp['AbstractText']=='':
		print(resp['Heading']+' ('+resp['AbstractSource']+'): '+resp['AbstractText']+'\n')
	if not resp['Definition']=='':
		print('Definition ('+resp['DefinitionSource']+'): '+resp['Definition']+'\n')
	if len(resp['RelatedTopics'])>0:
		print('Related Topics: ')
		for s in resp['RelatedTopics']:
			if s.has_key('Text'):
				print('\t'+s['Text'])
		print('\n')
	if len(resp['Results'])>0:
		print('Links: ')
		for s in resp['Results']:
			if s.has_key('Text'):
				print('\t'+s['Text'])
		print('\n')
	if not resp['Answer']=='':
		print(resp['AnswerType']+': '+resp['Answer']+'\n')
	
	
if len(sys.argv)>1:
	query=''
	for i in range(1,len(sys.argv)):
		query=query+sys.argv[i]+' '
	search(query)
else:
	while True:
		try:
			l = raw_input(">>")
			if not l.strip():
				continue
			search(l)
		except:
			print('\n')
			break
