#!/usr/bin/python
'''
This python script enables the user to query the MediaWiki API through the 
command line. The search returns (in order of preference) :
-a matching page title
-automatic redirect to an existing page
-first result from a Search API query

Usage:
	wik media wiki --> one-time search
	wik	--> interactive mode with history
'''
import os
import sys
import urllib
import re
import json
if not os.name=='nt':
	import readline #enables arrow keys and history
	
def removeBraces(l):
	res=''
	count=0
	pos=0
	for i in range(0,len(l)):
		if l[i]=='{':
			if count==0:
				res+=l[pos:i]
			count+=1
		elif l[i]=='}' and count>0:
			count-=1 
			if count==0:
				pos=i+1
	res+=l[pos:]
	return res
	
def search(query):
	f = urllib.urlopen("http://en.wikipedia.org/w/api.php?action=query&prop=revisions&rvprop=content&redirects&"+
		"format=xml&titles="+urllib.quote_plus(query))
	resp = f.read()
	ind = resp.find('<rev contentformat="text/x-wiki" contentmodel="wikitext" xml:space="preserve">')
	if ind<0:
		f=urllib.urlopen("http://en.wikipedia.org/w/api.php?action=opensearch&limit=1&"+
			"format=json&search="+urllib.quote_plus(query))
		resp = json.load(f)
		if len(resp[1])==0:
			print("No results returned")
		else:
			search(resp[1][0])
	else:
		ind=ind+78
		l=resp[ind:]
		l=re.sub("<.+?>",'', \
			re.sub("'''",'',\
			re.sub("''",'',\
			re.sub("&quot",'"',\
			re.sub("&lt",'<',\
			re.sub("&gt",'>',\
			re.sub("&amp",'&',\
			re.sub(";",'',\
			re.sub("\[[\s\S]*?\]",'',\
			re.sub("\[\[",'',\
			re.sub("\]\]",'',\
			re.sub("&lt;ref&gt;[\s\S]*?&lt;/ref&gt;",'', \
			removeBraces(l) \
			))))))))))))
		ref = re.findall("'[\s\S]+?' may (also )?refer to:",l)
		if len(ref)==0:
			l=l[:l.find('==')]
		print('\n'+l.lstrip().rstrip()+'\n')
	
if len(sys.argv)>1:
	query=''
	for i in range(1,len(sys.argv)):
		query=query+sys.argv[i]+' '
	search(query)
else:
	while True:
		try:
			l = raw_input(">>")
			if not l.strip():
				continue
			search(l)
		except KeyboardInterrupt:
			print('\n')
			break
